version: "3.7"

services:
  backend:
    container_name: backend_local
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./env_dir/.env.local.backend
    depends_on:
      - db

  frontend:
    container_name: frontend_local
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    command: npm run serve
    volumes:
      - ./frontend/:/app
    env_file:
      - ./env_dir/.env.local.frontend

  db:
    container_name: postgres_local
    image: postgres:latest
    env_file:
      - ./env_dir/.env.local.db
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - test_db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  # postgres_data:
  #   external: true
  test_db:
    external: true
