# 軽量のpythonコンテナを使用
# Djangoのセットアップ用に立ち上げるコンテナ
FROM python:3.10.0-slim-bullseye

# ホームディレクトリの作成
RUN mkdir -p /usr/src/app
ENV HOME=/usr/src/app
WORKDIR $HOME

# apt-getの更新
RUN apt-get update

# pipの更新
RUN pip install --upgrade pip
